apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuation-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "continuation-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "continuation-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
