apiVersion: v1
kind: Service
metadata:
  name: {{ include "cart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "cart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cart.selectorLabels" . | nindent 4 }}
    {{- if .Values.ha.enabled }}
    {{ include "cart.name" . }}-active: "true"   # 只选 leader pod(ha-gate 打的 active 标签)
    {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
